version: "3"

services:
    web:
        build: ./
        restart: on-failure:5 
        command: gunicorn settings.wsgi:application -w 3 --bind 0.0.0.0:8000 
        ports: 
          - 8000
        volumes: 
          - ./:/usr/src/code/

    nginx:
        image: nginx:alpine
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./staticfiles:/var/www/staticfiles
        ports:
            - 80:80
        depends_on:
          - web
