# Generated by Django 4.0.1 on 2022-01-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "A user with that email already exists."},
                help_text="Should be a valid email address",
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        ),
    ]
