# Generated by Django 4.0 on 2021-12-23 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=255,
                        unique=True,
                        verbose_name="Path for short URL",
                    ),
                ),
                ("destination_url", models.TextField(verbose_name="Destination URL")),
                (
                    "visits",
                    models.IntegerField(default=0, verbose_name="Number of visits"),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created on"),
                ),
                (
                    "updated_on",
                    models.DateTimeField(auto_now=True, verbose_name="Updated on"),
                ),
            ],
            options={
                "verbose_name": "destination",
                "verbose_name_plural": "destinations",
                "ordering": ["-created_on"],
            },
        ),
    ]
