# Generated by Django 4.0 on 2022-01-11 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_managers"),
        ("durls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="destination",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.customuser",
            ),
            preserve_default=False,
        ),
    ]
