name: Deploy to Demo server

on:
  push:
    branches: [ demo ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip pipenv
        pipenv install --dev

    - name: Run Tests
      run: |
        make test

    - name: Deploy to Demo server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          whoami
          cd ${{ secrets.DIRECTORY }}
          git checkout demo
          git fetch origin demo
          git reset --hard origin/demo
          make prod
          make migrate
